### ISSUE TITLE
PlayAsync throwing exception

### ISSUE THREAD

**Issue by dotZesshan** [skrusty/AsterNET.ARI#71]
I am trying to run 

`await sender.Channels.PlayAsync(e.Channel.Id, "sound:custom/After-Lineup", null, null, null, e.Channel.Id);`

in callback function `OnStasisStartEvent`

but everytime this line is executed following exception come and the music does not play. I have already check the sound file exist on correct path. Please guide me what the issue here? let me know if you need more info on this

```
2020-03-09 18:13:23,018 [8] ERROR Connector - c_OnStasisStartEventAsync|Exception:System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at RestSharp.Portable.HttpClient.Impl.Http.DefaultHttpResponseMessage.EnsureSuccessStatusCode()
   at RestSharp.Portable.RestClientBase.<ExecuteRequest>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestSharp.Portable.RestClientBase.<Execute>d__59`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AsterNET.ARI.Middleware.Default.RestActionConsumer.<ProcessRestTaskCommand>d__5`1.MoveNext() in F:\Projects\Github\AsterNET.ARI\AsterNET.ARI\Middleware\Default\RESTActionConsumer.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AsterNET.ARI.ARIBaseAction.<ExecuteTask>d__5`1.MoveNext() in F:\Projects\Github\AsterNET.ARI\AsterNET.ARI\ARI_1_0\Actions\ARIBaseAction.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AsterNET.ARI.Actions.ChannelsActions.<PlayAsync>d__49.MoveNext() in F:\Projects\Github\AsterNET.ARI\AsterNET.ARI\ARI_1_0\Actions\ChannelsActions.cs:line 1588
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at vQubeConnector.vQubeAriConnector.<c_OnStasisStartEventAsync>d__11.MoveNext() in C:\Users\Zeeshan\Documents\GitHub\vQube\vQube\vQubeAriConnector.cs:line 76
```

**Comment by dotZesshan** [comment]
@skrusty can you please help me with this? I will be very thankful.
